name: proxima-2025
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=3_kmp_llvm
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - absl-py=2.1.0=py310h06a4308_0
  - aiohappyeyeballs=2.4.4=py310h06a4308_0
  - aiohttp=3.11.10=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alsa-lib=1.2.8=h166bdaf_0
  - amply=0.1.6=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - ase=3.25.0=pyhd8ed1ab_0
  - astunparse=1.6.3=py_0
  - async-timeout=5.0.1=py310h06a4308_0
  - attr=2.5.1=h166bdaf_1
  - attrs=24.3.0=py310h06a4308_0
  - blas=1.0=mkl
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py310hf71b8c6_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cached-property=1.5.2=py_0
  - cachetools=5.5.1=py310h06a4308_0
  - cairo=1.16.0=he5ede1b_6
  - certifi=2025.11.12=py310h06a4308_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - coin-or-cbc=2.10.12=h8b142ea_1
  - coin-or-cgl=0.60.7=h516709c_0
  - coin-or-clp=1.17.8=h1ee7a9c_0
  - coin-or-osi=0.108.10=haf5fa05_0
  - coin-or-utils=2.11.11=hee58242_0
  - coincbc=2.10.12=4_metapackage
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h3788b33_0
  - cpython=3.10.17=py310hd8ed1ab_0
  - cryptography=41.0.3=py310h130f0dd_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=h9c0eb46_1
  - dbus=1.13.18=hb2f20db_0
  - dkh=1.2=ha94c79b_3
  - dnspython=2.4.2=py310h06a4308_0
  - docutils=0.22.2=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - dscribe=2.1.1=py310h3788b33_1
  - expat=2.7.0=h5888daf_0
  - f90wrap=0.2.16=py310h127553b_1
  - fftw=3.3.10=nompi_hf1063bd_110
  - flask=3.1.1=pyhd8ed1ab_0
  - flatbuffers=24.12.23=h8f4948b_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.1=h4c34cd2_2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.0=py310h89163eb_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.5.0=py310h5eee18b_0
  - future=1.0.0=pyhd8ed1ab_2
  - gast=0.4.0=pyhd3eb1b0_0
  - gau2grid=2.0.7=h4bc722e_4
  - gettext=0.24.1=h5888daf_0
  - gettext-tools=0.24.1=h5888daf_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310he8512ff_0
  - google-auth=2.38.0=py310h06a4308_1
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.13=h59595ed_1003
  - grpc-cpp=1.48.2=h5bf31a4_0
  - grpcio=1.48.2=py310h5bf31a4_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gstreamer-orc=0.4.41=h5eee18b_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.12.1=py310hc0802c4_0
  - harfbuzz=2.4.0=hca77d97_0
  - hdf5=1.12.1=h70be1eb_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=58.2=he6710b0_3
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jack=1.9.22=h11f4161_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - keras=2.12.0=py310h06a4308_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py310h3788b33_0
  - krb5=1.20.1=h568e23c_1
  - lame=3.100=h7b6447c_0
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.3=h6a678d5_0
  - libasprintf=0.24.1=h8e693c7_0
  - libasprintf-devel=0.24.1=h8e693c7_0
  - libblas=3.9.0=20_linux64_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.66=ha37c62d_0
  - libcblas=3.9.0=20_linux64_mkl
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.3.3=h36d4200_3
  - libcurl=8.2.1=h91b91d3_0
  - libdb=6.2.32=h6a678d5_1
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libecpint=1.0.7=h981d57b_12
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h9b69904_4
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgcrypt=1.11.1=ha770c72_0
  - libgcrypt-devel=1.11.1=hb9d3cd8_0
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgcrypt-tools=1.11.1=hb9d3cd8_0
  - libgettextpo=0.24.1=h5888daf_0
  - libgettextpo-devel=0.24.1=h5888daf_0
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran-ng=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libglib=2.78.4=hdc74915_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.9.1=hd6dc26d_0
  - libiconv=1.18=h4ce23a2_1
  - libint=2.9.0=h2b4839b_3
  - libjpeg-turbo=2.1.4=h166bdaf_0
  - liblapack=3.9.0=20_linux64_mkl
  - liblapacke=3.9.0=20_linux64_mkl
  - libllvm14=14.0.6=hecde1de_4
  - libllvm15=15.0.7=hadd5161_1
  - liblzma=5.8.1=hb9d3cd8_1
  - liblzma-devel=5.8.1=hb9d3cd8_1
  - libnghttp2=1.52.0=ha637b67_1
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=h27cfd23_1
  - libopengl=1.7.0=ha4b6fd6_2
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=hd590300_0
  - libpcm=1.2.3=h4175798_8
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=h37d81fd_1
  - libprotobuf=3.20.3=he621ea3_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libsystemd0=252=h2a991cd_0
  - libtiff=4.7.0=hde9077f_0
  - libtool=2.4.7=h6a678d5_0
  - libudev1=253=h0b41bf4_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libwebp-base=1.5.0=h851e524_0
  - libxc-c=6.2.2=cpu_h20a523f_6
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hcbfbd50_0
  - libxslt=1.1.37=h873f0b0_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=20.1.5=h024ca30_0
  - llvmlite=0.43.0=py310h6a678d5_1
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.8=py310h06a4308_0
  - markdown-it-py=2.2.0=py310h06a4308_1
  - markupsafe=3.0.2=py310h89163eb_1
  - matminer=0.9.3=pyhd8ed1ab_1
  - matplotlib=3.10.0=py310h06a4308_0
  - matplotlib-base=3.10.0=py310hbfdbfaf_0
  - mdurl=0.1.0=py310h06a4308_0
  - mkl=2023.2.0=h84fe81f_50496
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - ml_dtypes=0.4.1=py310hc74f9fe_0
  - monty=2025.3.3=pyhd8ed1ab_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.0=py310h3788b33_0
  - multidict=6.1.0=py310h5eee18b_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=5.7.24=he378463_2
  - mysql-common=8.0.32=h14678bc_0
  - mysql-libs=8.0.32=h54cf53e_0
  - namex=0.0.7=py310h06a4308_0
  - narwhals=1.40.0=pyhe01879c_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.3=py310h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numba=0.60.0=py310h5dc88bb_0
  - numpy=1.23.5=py310h5f9d8c6_1
  - numpy-base=1.23.5=py310hb5e798b_1
  - oauthlib=3.2.2=py310h06a4308_0
  - openbabel=3.1.1=py310heaf86c6_5
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.5.5=h2aa78c0_1
  - openssl=1.1.1w=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optking=0.3.0=pyhd8ed1ab_0
  - optree=0.14.1=py310hdb19cb5_0
  - packaging=25.0=pyh29332c3_1
  - palettable=3.3.3=pyhd8ed1ab_1
  - pandas=2.2.3=py310h5eaa309_3
  - pcmsolver=1.2.3=py_15
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py310hac6e08b_1
  - pint=0.24.4=pyhd8ed1ab_1
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.0=h29eaf8c_0
  - platformdirs=4.3.8=pyhe01879c_0
  - plotly=6.1.1=pyhd8ed1ab_0
  - ply=3.11=py310h06a4308_0
  - propcache=0.3.1=py310h5eee18b_0
  - protobuf=3.20.3=py310h6a678d5_0
  - psi4=1.9.1=py310h86d0350_7
  - psutil=7.0.0=py310ha75aee5_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio=16.1=h4ab2085_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pybtex=0.24.0=pyhd8ed1ab_3
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.4=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py310hbcd0ec0_0
  - pygments=2.19.1=py310h06a4308_0
  - pyjwt=2.10.1=py310h06a4308_0
  - pymatgen=2024.3.1=py310h1f7b6fc_0
  - pymongo=4.11=py310hf71b8c6_0
  - pyopenssl=23.2.0=py310h06a4308_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyqt=5.15.10=py310h6a678d5_1
  - pyqt5-sip=12.13.0=py310h5eee18b_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.13=h7a1cb2a_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-flatbuffers=24.3.25=py310h06a4308_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h89163eb_2
  - qcelemental=0.29.0=pyhd8ed1ab_1
  - qcengine=0.32.0=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.2=h5b8104b_9
  - quippy=0.9.14=py310h6c23d3c_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_1
  - requests-oauthlib=2.0.0=py310h06a4308_0
  - rich=13.9.4=py310h06a4308_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - ruamel.yaml=0.18.10=py310ha75aee5_0
  - ruamel.yaml.clib=0.2.8=py310ha75aee5_1
  - scipy=1.15.2=py310h1d65ade_0
  - setuptools=80.8.0=pyhff2d567_0
  - sip=6.7.12=py310h6a678d5_1
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.1.10=h6a678d5_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sparse=0.17.0=pyhcf101f3_0
  - spglib=2.6.0=py310h1e9006d_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.14.0=pyh2585a3b_105
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.12.1=py310h06a4308_0
  - tensorboard-data-server=0.7.0=py310h52d8a92_1
  - tensorboard-plugin-wit=1.8.1=py310h06a4308_0
  - tensorflow=2.12.0=mkl_py310hc7ea715_0
  - tensorflow-base=2.12.0=mkl_py310he5f8e37_0
  - tensorflow-estimator=2.12.0=py310h06a4308_0
  - termcolor=2.1.0=py310h06a4308_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=py310h06a4308_0
  - tornado=6.5.1=py310ha75aee5_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.13.2=h0e9735f_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - uncertainties=3.2.3=pyhd8ed1ab_0
  - unicodedata2=16.0.0=py310ha75aee5_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_1
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.0=py310h5eee18b_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-compositeproto=0.4.2=hb9d3cd8_1002
  - xorg-damageproto=1.2.1=hb9d3cd8_1003
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=h5eee18b_1003
  - xorg-kbproto=1.0.7=h5eee18b_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=h0b41bf4_1
  - xorg-libxcursor=1.2.0=h0b41bf4_1
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-libxxf86vm=1.1.5=h0b41bf4_0
  - xorg-randrproto=1.5.0=hb9d3cd8_1002
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-util-macros=1.19.0=h27cfd23_2
  - xorg-xextproto=7.3.0=h5eee18b_1004
  - xorg-xorgproto=2024.1=h5eee18b_0
  - xorg-xproto=7.0.31=h5eee18b_1008
  - xz=5.8.1=hbcc6ac9_1
  - xz-gpl-tools=5.8.1=hbcc6ac9_1
  - xz-tools=5.8.1=hb9d3cd8_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.18.0=py310h5eee18b_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py310ha75aee5_2
  - zstd=1.5.6=hc292b87_0
  - pip:
      - argparse-dataclass==2.0.0
      - bel-resources==0.0.3
      - bioregistry==0.13.8
      - click-plugins==1.1.1.2
      - cloudpickle==3.1.1
      - configargparse==1.7.1
      - connection-pool==0.0.3
      - curies==0.12.4
      - datrie==0.8.3
      - dpath==2.2.0
      - email-validator==2.3.0
      - farama-notifications==0.0.4
      - fastjsonschema==2.21.2
      - greenlet==3.2.4
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.1.1
      - humanfriendly==10.0
      - humanize==4.14.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.8.1
      - more-click==0.1.3
      - more-itertools==10.8.0
      - multisplitby==0.0.1
      - nbformat==5.10.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - psycopg2-binary==2.9.11
      - pulp==3.3.0
      - pystow==0.7.11
      - python-git-info==0.8.3
      - ratelimit==2.2.1
      - referencing==0.36.2
      - requests-file==3.0.1
      - reretry==0.11.8
      - rpds-py==0.27.1
      - scikit-learn==1.7.2
      - shimmy==2.0.0
      - smart-open==7.3.1
      - snakemake==7.32.4
      - sqlalchemy==2.0.44
      - stable-baselines3==2.6.0
      - stopit==1.1.2
      - throttler==1.2.2
      - toposort==1.10
      - torch==2.7.1
      - traitlets==5.14.3
      - triton==3.3.1
      - yte==1.9.0
prefix: /home/trentonjw/.conda/envs/proxima-2025
